### PR TITLE
Support Resque >= v1.9.10 and Limit fork job processing by job limit or time limit.

### PR DESCRIPTION
**Pull request by lantins**
Hey,

I've refactored the plugin to work with Resque v1.9.10 and above.

This is done by hooking into the `#shutdown?` and `#perform` methods of Resque::Worker.
- After the first fork, the child process is hijacked!
- It uses @cant_fork (checked in `#fork`) to prevent exiting from the child and process another job.
- Once the job limit / time limit is reached, the child exits and the process repeats.

I've also added the ability to limit fork queue processing using either `JOBS_PER_FORK` or `MINUTES_PER_FORK`.
If you don't set either environment variable, it defaults to a 1 minute time limit per fork.

The unit tests also run much faster now.

Please, let me know what you think!?

If you merge the changes, I'll happily update the README and add some yardoc's.

Thanks =)

Luke

### CODE REVIEW

**Comment by staugaard** [comment]
Hi,

That sounds great. I've been meaning to update for new resque versions.

I'm pretty busy at the moment, but I will review your work and pull.

Thanks for your contribution!

Mick

**Comment by lantins** [comment]
FYI... the README was updated in my `personal_gem` branch (as markdown though), along with a whole bunch of other changes you probably don't want ;-)

Thanks for the reply!

Luke

**Comment by grosser** [comment]
not merged yet, should not be closed...

**Comment by lantins** [comment]
Hey Mick,

Any thoughts on accepting the pull request?

I've been using these changes myself since posting the patch request, without any issues (that I've noticed anyhow).

Cheers.

Luke

**Comment by grosser** [comment]
i think the repo is dead / owner does not care anymore, long live the forks :)

**Comment by lantins** [comment]
If that is indeed the case, I'd like to see the 'canonical repo' moved to one of the forks.
And for the owner to be given access to release new rubygems.

I'll throw my hat in the ring for the job, should Mick decide to do that...

**Comment by staugaard** [comment]
Hi,

I'm very sorry about this guys. I just tried pulling in you changes, and can not get the tests to pass.

I can give you push access to the the gem on gemcutter/rubygems and link we can make your fork the new official one.

Please provide me with your email address, and I'll give you push access.

**Comment by staugaard** [comment]
I found out that test did not pass on resque 1.9.10, but on 1.10 they are good.

I've merged in your changes and updated the gemspec

**Comment by lantins** [comment]
Not too sure why I got v1.9.10 and v1.10.0 confused, apologies for that!

Thanks for pulling the changes =)

Would you still like to change the 'canonical' repo to mine? My email is luke@lividpenguin.com

**Pull request merged**
